config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users

  resources :users
  resources :products do
    collection do
      get 'catalog'
      get 'autocomplete'
      get 'my_products', to: 'products#index', defaults: { mine: true }
    end
    resources :reviews, only: [:create]
    resources :ratings, only: [:create]
  end

  resources :purchases do
    member do
      get 'confirmation', to: 'purchases#confirmation', as: 'confirmation'
    end
    collection do
      get 'checkout', to: 'purchases#checkout', as: 'checkout'
    end
  end

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: 'add_to'
    post 'remove/:product_id', to: 'carts#remove', as: 'remove_from'
    patch 'update_item/:id', to: 'carts#update', as: 'update_item'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon px-5">
    <div class="container-fluid">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "logo-b.svg" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Catálogo', catalog_products_path, class: "nav-link btn btn-link my-2 mx-1 rounded-pill" %>
          </li>
          <li class="nav-item">
            <%= link_to new_product_path, class: "nav-link btn btn btn-link my-2 mx-1 rounded-pill" do %>
              Vender
            <% end %>
          </li>
        </ul>

        <div class="d-flex align-items-center ms-auto">
          <% if user_signed_in? %>
            <%= link_to products_path, class: "btn btn-light my-2 mx-1 rounded-pill" do %>
              <i class="fa-solid fa-dolly"></i> Mi inventario
            <% end %>
            <li class="nav-item dropdown list-unstyled mx-4 badge text-bg-light rounded-pill pe-4">
              <a href="#" class="nav-link d-flex align-items-center" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="avatar rounded-circle me-2 d-flex align-items-center justify-content-center" style="background-color: <%= user_color(current_user) %>;">
                  <span class="text-white"><%= current_user.email[0].upcase %></span>
                </div>
                <span><%= current_user.email.split('@').first.capitalize %></span>
              </a>
              <div class="dropdown-menu mx-3 my-2" aria-labelledby="navbarDropdown">
                <%= link_to "Configuración", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </div>
            </li>
            <%= link_to cart_path, class: "btn btn-light position-relative ms-3 rounded-pill mx-3" do %>
              <i class="fas fa-shopping-cart"></i>
              <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-primary">
                <%= current_cart.cart_items.sum(:quantity) %>
              </span>
            <% end %>
          <% else %>
            <%= link_to new_user_session_path, class: "btn btn-outline-primary me-2 rounded-pill" do %>
              Login
            <% end %>
            <%= link_to new_user_registration_path, class: "btn btn-primary rounded-pill text-white" do %>
              Sign-up
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_product_card.html.erb
<div class="card mb-3 card-rounded" style="width: 24rem;">
  <% if product && product.image.attached? %>
    <%= cl_image_tag product.image.key, class: "card-img-top fixed-size-image", alt: product.model, style: "width: 100%; height: 300px; object-fit: cover;" %>
  <% else %>
    <%= image_tag 'default_image.jpg', class: "card-img-top fixed-size-image", alt: product ? product.model : 'Producto', style: "width: 100%; height: 300px; object-fit: cover;" %>
  <% end %>
  <div class="card-body d-flex flex-column">
    <h5 class="card-title text-center"><%= product ? product.model : 'Producto' %></h5>
    <div class="d-flex justify-content-center mb-3">
      <span class="badge rounded-pill text-bg-primary"><%= product ? product.category.name : 'Categoría' %></span>
    </div>
    <p class="card-text text-center flex-grow-1"><%= product ? product.description : 'Descripción' %></p>
    <div class="d-flex justify-content-center mb-3">
      <span class="badge bg-light text-dark">Stock: <%= product ? product.quantity_available : 'N/A' %></span>
      <span class="badge bg-light text-dark">Talla: <%= product ? product.size : 'N/A' %></span>
      <span class="badge bg-light text-dark">Marca: <%= product ? product.brand : 'N/A' %></span>
      <span class="badge bg-light text-dark">Año: <%= product ? product.release_date.year : 'N/A' %></span>
    </div>
    <h5 class="card-price text-center mb-3"><%= product ? number_to_currency(product.price) : 'Precio' %></h5>
    <a href="<%= product_path(product) %>" class="btn btn-outline-secondary rounded-pill w-100 mb-2">Ver Producto</a>
    <%= button_to 'Comprar', add_to_cart_path(product), method: :post, class: "btn btn-primary rounded-pill w-100 mb-2" %>
  </div>
</div>