config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users

  resources :users
  resources :products do
    collection do
      get 'catalog'
      get 'autocomplete'
      get 'my_products', to: 'products#index', defaults: { mine: true }
    end
    resources :reviews, only: [:create]
    resources :ratings, only: [:create]
  end

  resources :purchases do
    member do
      get 'confirmation', to: 'purchases#confirmation', as: 'confirmation'
    end
    collection do
      get 'checkout', to: 'purchases#checkout', as: 'checkout'
    end
  end

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: 'add_to'
    post 'remove/:product_id', to: 'carts#remove', as: 'remove_from'
    patch 'update_item/:id', to: 'carts#update', as: 'update_item'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy

  def add_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    if current_item
      if current_item.quantity < product.quantity_available
        current_item.increment(:quantity)
      else
        current_item.errors.add(:base, "No hay suficiente stock disponible para agregar más de este producto.")
      end
    else
      current_item = cart_items.build(product_id: product.id, quantity: 1)
    end
    current_item.save
    current_item
  end

  def remove_product(product)
    current_item = cart_items.find_by(product_id: product.id)
    return unless current_item

    current_item.decrement(:quantity)
    current_item.save if current_item.quantity.positive?
    current_item.destroy if current_item.quantity <= 0
  end

  def total_price
    cart_items.joins(:product).sum('products.price * cart_items.quantity')
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end

  def add
    @cart = current_cart
    product = Product.find(params[:product_id])
    item = @cart.add_product(product)

    if item.save
      flash[:notice] = 'Producto agregado al carrito.'
    else
      flash[:alert] = item.errors.full_messages.to_sentence
    end

    redirect_to cart_path
  end

  def remove
    @cart = current_cart
    item = @cart.cart_items.find_by(product_id: params[:product_id])
    item&.destroy
    redirect_to cart_path
  end

  def update
    @cart = current_cart
    item = @cart.cart_items.find(params[:id])
    if params[:quantity].to_i <= item.product.quantity_available
      item.update(quantity: params[:quantity]) if params[:quantity].to_i.positive?
    else
      flash[:alert] = "No hay suficiente stock disponible para actualizar la cantidad."
    end
    redirect_to cart_path
  end

  private

  def current_cart
    @current_cart ||= Cart.find(session[:cart_id]) if session[:cart_id]
    if @current_cart.nil?
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
end

app/views/carts/show.html.erb
<div class="container my-5">
  <h1 class="fs-2 font-weight-bold">Tu carrito</h1>
  <p><%= pluralize(@cart.cart_items.count, 'producto') %> en total</p>

  <div class="row">
    <div class="col-md-8">
      <% @cart.cart_items.each do |item| %>
        <div class="card mb-3 card-rounded " style="width: 100%;">
          <div class="row g-0">
            <div class="col-md-4 fixed-size-image">
              <% if item.product.image.attached? %>
                <%= cl_image_tag item.product.image.key, class: "img-fluid fixed-size-image", alt: item.product.model, style: "width: 100%; height: 300px; object-fit: cover;" %>
              <% else %>
                <%= image_tag 'default_image.jpg', class: "img-fluid fixed-size-image", alt: item.product.model, style: "width: 100%; height: 300px; object-fit: cover;" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= item.product.model %></h5>
                <p class="card-text"><small class="text-muted"><%= item.product.description %></small></p>
                <p class="card-text">Marca: <%= item.product.brand %></p>
                <p class="card-text">Talla: <%= item.product.size %></p>
                <p class="card-text">Año: <%= item.product.release_date.year %></p>
                <p class="card-text"><strong><%= number_to_currency(item.product.price) %></strong></p>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <% if item.quantity && item.quantity > 1 %>
                      <%= button_to '-', update_item_cart_path(item, quantity: item.quantity - 1), method: :patch, class: 'btn btn-outline-secondary rounded-pill btn-sm' %>
                    <% else %>
                      <%= button_to '-', update_item_cart_path(item, quantity: 1), method: :patch, class: 'btn btn-outline-secondary rounded-pill btn-sm', disabled: true %>
                    <% end %>
                    <span class="mx-2"><%= item.quantity %></span>
                    <%= button_to '+', update_item_cart_path(item, quantity: item.quantity + 1), method: :patch, class: 'btn btn-outline-secondary rounded-pill btn-sm', disabled: (item.quantity >= item.product.quantity_available) %>
                  </div>
                  <%= button_to 'Eliminar', remove_from_cart_path(item.product), method: :post, class: 'btn btn-outline-danger px-4 rounded-pill btn-sm' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-md-4">
      <div class="card card-rounded ">
        <div class="card-body">
          <h5 class="card-title">Resumen del pedido</h5>
          <p class="card-text ">Productos (<%= @cart.cart_items.count %>): <%= number_to_currency(@cart.cart_items.sum { |item| item.product.price * item.quantity }) %></p>
          <hr>
          <h5 class="card-title">Subtotal incl. IVA</h5>
          <p class="card-text display-4"><strong><%= number_to_currency(@cart.cart_items.sum { |item| item.product.price * item.quantity }) %></strong></p>
          <%= link_to 'Ir a pagar', checkout_purchases_path(cart_id: @cart.id), class: 'btn btn-primary rounded-pill btn-lg w-100 mt-3' %>
          <div class="my-4 d-flex justify-content-center">
            <%= image_tag 'visa.svg', alt: 'Visa', class: 'img-fluid mx-2', style: 'width: 40px;' %>
            <%= image_tag 'mastercard.svg', alt: 'Mastercard', class: 'img-fluid mx-2', style: 'width: 40px;' %>
            <%= image_tag 'amex.svg', alt: 'Amex', class: 'img-fluid mx-2', style: 'width: 40px;' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>