config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users

  resources :users
  resources :products do
    collection do
      get 'catalog'
      get 'autocomplete'
      get 'my_products', to: 'products#index', defaults: { mine: true }
    end
    resources :reviews, only: [:create]
    resources :ratings, only: [:create]
  end

  resources :purchases do
    member do
      get 'confirmation', to: 'purchases#confirmation', as: 'confirmation'
    end
    collection do
      get 'checkout', to: 'purchases#checkout', as: 'checkout'
    end
  end

  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: 'add_to'
    post 'remove/:product_id', to: 'carts#remove', as: 'remove_from'
    patch 'update_item/:id', to: 'carts#update', as: 'update_item'
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_attributes,
                  against: %i[model description brand],
                  associated_against: {
                    category: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
  belongs_to :user
  belongs_to :category
  has_many :purchases
  has_many :reviews, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_one_attached :image

  before_validation :sanitize_price

  validates :price, :description, :model, :brand, :release_date, :quantity_available, :size, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity_available,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 999_999 }

  def average_rating
    if ratings.count.positive?
      ratings.average(:score).to_f.round(2)
    else
      0
    end
  end

  private

  def sanitize_price
    return unless price.present?

    self.price = price.to_s.gsub(/[^0-9.]/, '').to_f
  end
end

app/controllers/products_controller.rb
# app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: %i[show catalog autocomplete]
  before_action :set_product, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @products = current_user.products
  end

  def catalog
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(product_params)
    if @product.save
      redirect_to @product, notice: 'Producto creado exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Producto actualizado exitosamente.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Producto eliminado exitosamente.'
  end

  def autocomplete
    if params[:query].present?
      @products = Product.search_by_attributes(params[:query]).limit(3)
    else
      @products = Product.none
    end

    respond_to do |format|
      format.json { render json: @products.to_json(only: %i[id model brand price], methods: [:image_url]) }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:category_id, :price, :description, :model, :brand, :image, :release_date,
                                    :quantity_available, :size)
  end

  def authorize_user!
    redirect_to products_path, alert: 'No autorizado' unless @product.user == current_user
  end
end

app/views/products/catalog.html.erb
<div class="container mt-5 px-5">
  <div class="text-center mb-4">
    <h1 class="display-4 fw-bold">Catálogo de Productos</h1>
    <p class="lead">Explora nuestra exclusiva colección de ropa y accesorios.</p>
  </div>

  <div class="row justify-content-center">
    <% @products.each do |product| %>
      <div class="col-lg-4 col-md-6 col-sm-12 mb-4 d-flex">
        <%= render partial: 'shared/product_card', locals: { product: product } %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-7">
      <h2>Editar Producto</h2>
      <%= form_with model: @product, local: true, id: "product_form" do |form| %>
        <% if @product.errors.any? %>
          <div class="alert alert-danger">
            <h4>Errores</h4>
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!-- Dropdown de Categorías -->
        <div class="mb-3">
          <%= form.label :category_id, "Categoría" %>
          <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Seleccione una categoría" }, { class: "form-control", id: "product_category_id" } %>
        </div>

        <div class="mb-3">
          <%= form.label :model %>
          <%= form.text_field :model, class: "form-control", id: "product_model" %>
        </div>
        <div class="mb-3">
          <%= form.label :size, "Talla" %><br>
          <div id="size_radio_buttons" class="btn-group" role="group" aria-label="Talla">
            <!-- The radio buttons will be dynamically added here -->
          </div>
        </div>
        <div class="mb-3">
          <%= form.label :brand %>
          <%= form.text_field :brand, class: "form-control", id: "product_brand" %>
        </div>
        <div class="mb-3">
          <%= form.label :release_date %>
          <%= form.date_field :release_date, class: "form-control", id: "product_release_date" %>
        </div>
        <div class="mb-3">
          <%= form.label :stock %>
          <%= form.number_field :quantity_available, class: "form-control", id: "product_quantity_available", maxlength: 6, oninput: "this.value=this.value.slice(0,6)" %>
        </div>
        <div class="mb-3">
          <%= form.label :price %>
          <%= form.number_field :price, class: "form-control", id: "product_price", step: "0.01", min: "0" %>
        </div>
        <div class="mb-3">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control", id: "product_description", maxlength: 120 %>
          <small id="description_counter" class="form-text text-muted"><%= 120 - @product.description.length %> caracteres restantes</small>
        </div>
        <div class="mb-3">
          <%= form.label :image, "Nueva Imagen" %>
          <%= form.file_field :image, class: "form-control", id: "product_image" %>
        </div>
        <%= form.submit "Actualizar", class: "btn btn-primary rounded-pill" %>
      <% end %>
    </div>
    <div class="col-md-5">
      <h2>Mi producto</h2>
      <div class="card mb-3 shadow-sm card-rounded" style="width: 24rem;">
        <% if @product.image.attached? %>
          <%= cl_image_tag @product.image.key, id: "preview_image", class: "card-img-top fixed-size-image", style: "width: 100%; height: 300px; object-fit: cover;" %>
        <% else %>
          <%= image_tag 'default_image.jpg', id: "preview_image", class: "card-img-top fixed-size-image", style: "width: 100%; height: 300px; object-fit: cover;" %>
        <% end %>
        <div class="card-body d-flex flex-column">
          <h5 id="preview_model" class="card-title text-center"><%= @product.model %></h5>
          <div class="d-flex justify-content-center mb-3">
            <span id="preview_category" class="badge rounded-pill text-bg-primary"><%= @product.category.name %></span>
          </div>
          <p id="preview_description" class="card-text text-center flex-grow-1"><%= @product.description %></p>
          <div class="d-flex justify-content-center mb-3">
            <span id="preview_quantity_available" class="badge bg-light text-dark">Stock: <%= @product.quantity_available %></span>
            <span id="preview_size" class="badge bg-light text-dark">Talla: <%= @product.size %></span>
            <span id="preview_brand" class="badge bg-light text-dark">Marca: <%= @product.brand %></span>
            <span id="preview_release_date" class="badge bg-light text-dark">Año: <%= @product.release_date.year %></span>
          </div>
          <h5 id="preview_price" class="card-price text-center mb-3"><%= number_to_currency(@product.price)%></h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid mt-5 px-5">
  <div class=" mb-4">
    <h1>
      <span class="badge text-bg-light p-3 rounded-pill">
        <i class="fa-solid fa-dolly mx-2"></i>
      </span>
      Mi inventario
    </h1>
  </div>
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h2 class="fs-5">Listado de Productos</h2>
    <%= link_to 'Vender Producto', new_product_path, class: "btn btn-primary rounded-pill" %>
  </div>
  <div class="table-responsive">
    <table class="table table-hover align-middle">
      <thead class="table-light">
        <tr>
          <th>ID</th>
          <th>Imagen</th>
          <th>Modelo</th>
          <th>Marca</th>
          <th>Descripción</th>
          <th>Precio</th>
          <th>Cantidad Disponible</th>
          <th>Categoría</th>
          <th>Talla</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td>
              <% if product.image.attached? %>
                <%= cl_image_tag product.image.key, class: "img-thumbnail card-rounded", style: "width: 50px; height: 50px; object-fit: cover;" %>
              <% else %>
                <%= image_tag 'default_image.jpg', class: "img-thumbnail card-rounded", style: "width: 50px; height: 50px; object-fit: cover;" %>
              <% end %>
            </td>
            <td><%= product.model %></td>
            <td><%= product.brand %></td>
            <td><%= product.description %></td>
            <td><%= number_to_currency(product.price) %></td>
            <td><%= product.quantity_available %></td>
            <td><%= product.category.name %></td>
            <td><%= product.size %></td>
            <td>
              <%= link_to product_path(product), class: "btn btn-outline-primary btn-sm me-2 rounded-pill", title: 'Ver Producto', data: { toggle: 'tooltip', placement: 'top' } do %>
                <i class="fas fa-eye"></i>
              <% end %>
              <%= link_to edit_product_path(product), class: "btn btn-secondary text-white btn-sm me-2 rounded-pill", title: 'Editar', data: { toggle: 'tooltip', placement: 'top' } do %>
                <i class="fas fa-edit"></i>
              <% end %>
              <button class="btn btn-danger text-white btn-sm rounded-pill" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" data-product-id="<%= product.id %>" title="Eliminar" data-bs-toggle="tooltip" data-bs-placement="top">
                <i class="fas fa-trash-alt"></i>
              </button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<!-- Modal de confirmación de eliminación -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmDeleteModalLabel">Confirmar eliminación</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ¿Estás seguro de que deseas eliminar este producto?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary rounded-pill" data-bs-dismiss="modal">Cancelar</button>
        <%= form_with url: '', method: :delete, local: true, id: 'confirmDeleteForm' do %>
          <%= submit_tag 'Eliminar', class: 'btn btn-danger rounded-pill' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-7">
      <h2>Crear Nuevo Producto</h2>
      <%= form_with model: @product, local: true, id: "product_form" do |form| %>
        <% if @product.errors.any? %>
          <div class="alert alert-danger">
            <h4>Errores</h4>
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <!-- Dropdown de Categorías -->
        <div class="mb-3">
          <%= form.label :category_id, "Categoría" %>
          <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Seleccione una categoría" }, { class: "form-control", id: "product_category_id" } %>
        </div>

        <!-- Otros campos del formulario -->
        <div class="mb-3">
          <%= form.label :model %>
          <%= form.text_field :model, class: "form-control", id: "product_model" %>
        </div>
        <div class="mb-3">
          <%= form.label :size, "Talla" %><br>
          <div id="size_radio_buttons" class="btn-group" role="group" aria-label="Talla">
            <!-- The radio buttons will be dynamically added here -->
          </div>
        </div>
        <div class="mb-3">
          <%= form.label :brand %>
          <%= form.text_field :brand, class: "form-control", id: "product_brand" %>
        </div>
        <div class="mb-3">
          <%= form.label :release_date %>
          <%= form.date_field :release_date, class: "form-control", id: "product_release_date" %>
        </div>
        <div class="mb-3">
          <%= form.label :stock %>
          <%= form.number_field :quantity_available, class: "form-control", id: "product_quantity_available", maxlength: 6, oninput: "this.value=this.value.slice(0,6)" %>
        </div>
        <div class="mb-3">
          <%= form.label :price %>
          <%= form.text_field :price, class: "form-control", id: "product_price", oninput: "formatPrice(this)" %>
        </div>
        <div class="mb-3">
          <%= form.label :description %>
          <%= form.text_area :description, class: "form-control", id: "product_description", maxlength: 120 %>
          <small id="description_counter" class="form-text text-muted">120 caracteres restantes</small>
        </div>
        <div class="mb-3">
          <%= form.label :image, "Imagen del Producto" %>
          <%= form.file_field :image, class: "form-control", id: "product_image" %>
        </div>
        <%= form.submit "Guardar", class: "btn btn-primary rounded-pill" %>
      <% end %>
    </div>
    <div class="col-md-5">
      <h2>Previsualización</h2>
      <div class="card mb-3 shadow-sm card-rounded" style="width: 24rem;">
        <img src="<%= asset_path('default_image.jpg') %>" id="preview_image" class="card-img-top fixed-size-image" style="width: 100%; height: 300px; object-fit: cover;">
        <div class="card-body d-flex flex-column">
          <h5 id="preview_model" class="card-title text-center"></h5>
          <div class="d-flex justify-content-center mb-3">
            <span id="preview_category" class="badge rounded-pill text-bg-primary"></span>
          </div>
          <p id="preview_description" class="card-text text-center flex-grow-1"></p>
          <div class="d-flex justify-content-center mb-3">
            <span id="preview_quantity_available" class="badge bg-light text-dark"></span>
            <span id="preview_size" class="badge bg-light text-dark"></span>
            <span id="preview_brand" class="badge bg-light text-dark"></span>
            <span id="preview_release_date" class="badge bg-light text-dark"></span>
          </div>
          <h5 id="preview_price" class="card-price text-center mb-3"></h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<main class="content-wrapper mt-5">
  <section class="container">
    <div class="row">
      <!-- Imagen -->
      <div class="col-md-6 pb-4 pb-md-0 mb-2 mb-sm-3 mb-md-0">
        <div class="position-relative">
          <% if @product.image.attached? %>
            <%= cl_image_tag @product.image.key, class: "img-fluid product-image", alt: @product.model, style: "width: 100%; height: auto; max-height: 600px; object-fit: cover;" %>
          <% else %>
            <%= image_tag 'default_image.jpg', class: "img-fluid rounded product-image", alt: @product.model, style: "width: 100%; height: auto; max-height: 600px; object-fit: cover;" %>
          <% end %>
        </div>
      </div>
      <!-- Contenido -->
      <div class="col-md-6">
        <div class="ps-md-4 ps-xl-5">
          <!-- rating - estrellas -->
          <a class="d-none d-md-flex align-items-center gap-2 text-decoration-none mb-3">
            <div class="d-flex gap-1 fs-sm">
              <!-- Estrellas de rating -->
              <%= 5.times.map do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
              <% end.join.html_safe %>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star" viewBox="0 0 16 16">
                <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z"/>
              </svg>
            </div>
            <span class="text-body-tertiary fs-sm">23 reviews</span>
          </a>
          <!-- Modelo, Descripción y Precio-->
          <h1 class="h3"><%= @product.model %></h1>
          <h6 class="mb-5"><%= @product.category.name %> - <%= @product.brand %></h6>
          <p class="fs-sm mb-0"><%= @product.description %></p>
          <div class="h4 d-flex align-items-center my-4">
            <%= number_to_currency(@product.price) %>
            <del class="fs-6 fw-normal text-body-tertiary ms-2"><%= number_to_currency(@product.price * 1.2) %></del>
          </div>
          <!-- Tallas -->
          <div class="pb-3 mb-2 mb-lg-3">
            <label class="form-label fw-semibold pb-1 mb-2">Size</label>
            <div class="d-flex flex-wrap gap-2">
              <input type="radio" class="btn-check rounded-pill" name="size-option" id="sz-1" checked>
              <label for="sz-1" class="btn btn-sm btn-outline-secondary flex-fill rounded-pill">S</label>
              <input type="radio" class="btn-check" name="size-option" id="sz-2">
              <label for="sz-2" class="btn btn-sm btn-outline-secondary flex-fill rounded-pill">M</label>
              <input type="radio" class="btn-check" name="size-option" id="sz-3">
              <label for="sz-3" class="btn btn-sm btn-outline-secondary flex-fill rounded-pill">L</label>
              <input type="radio" class="btn-check" name="size-option" id="sz-4">
              <label for="sz-4" class="btn btn-sm btn-outline-secondary flex-fill rounded-pill">XS</label>
              <input type="radio" class="btn-check" name="size-option" id="sz-5">
              <label for="sz-5" class="btn btn-sm btn-outline-secondary flex-fill rounded-pill">XM</label>
            </div>
          </div>
          <!-- Cantidad y Comprar -->
          <div class="d-flex align-items-center gap-3 pb-3 pb-lg-4 mb-3">
            <div class="d-flex align-items-center">
              <button type="button" class="btn btn-icon btn-lg d-flex justify-content-center align-items-center" data-decrement aria-label="Decrement quantity">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-dash" viewBox="0 0 16 16">
                  <path d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8"/>
                </svg>
              </button>
              <input type="number" class="form-control form-control-lg text-center mx-2 rounded-pill" min="1" value="1" readonly>
              <button type="button" class="btn btn-icon btn-lg d-flex justify-content-center align-items-center" data-increment aria-label="Increment quantity">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                  <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg>
              </button>
            </div>

            <%= form_with url: add_to_cart_path(product_id: @product.id), method: :post, class: "d-inline w-100" do %>
              <button type="submit" class="btn btn-lg btn-dark w-100 rounded-pill">Comprar</button>
            <% end %>

          </div>
          <!-- Campo oculto para la cantidad máxima -->
          <input type="hidden" id="max-quantity" value="<%= @product.quantity_available %>">

          <!-- detalles aleatorio -->
          <ul class="list-unstyled gap-3 pb-3 pb-lg-4 mb-3">
            <li class="d-flex flex-wrap fs-sm mb-4">
              <span class="d-flex align-items-center fw-medium text-dark-emphasis me-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar-check me-2" viewBox="0 0 16 16">
                  <path d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0"/>
                  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
                </svg>
                Fecha de Lanzamiento:
              </span>
              <%= @product.release_date %>.
            </li>
            <li class="d-flex flex-wrap fs-sm mb-4">
              <span class="d-flex align-items-center fw-medium text-dark-emphasis me-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock me-2" viewBox="0 0 16 16">
                  <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71z"/>
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16m7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0"/>
                </svg>
                Tiempo estimado de Entrega:
              </span>
              15 - 27 Jul, 2024.
            </li>
            <li class="d-flex flex-wrap fs-sm">
              <span class="d-flex align-items-center fw-medium text-dark-emphasis me-2">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-truck me-2" viewBox="0 0 16 16">
                  <path d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5zm1.294 7.456A2 2 0 0 1 4.732 11h5.536a2 2 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456M12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2"/>
                </svg>
                Entrega gratis:
              </span>
              Sobre compras mayores a 100 dólares.
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <section class="container pt-5 mt-2 mt-sm-3 mt-lg-4 mt-xl-5">
    <div class="reviews-section mt-5">

      <h4>Evaluaciones</h4>

      <% if user_signed_in? %>
        <%= form_with model: [@product, @product.reviews.build], url: product_reviews_path(@product), local: true do |form| %>
          <div class="form-group">
            <label for="rating">How would you rate your experience?</label>
            <div class="star-rating">
              <% 5.times do |i| %>
                <input type="radio" id="star<%= i+1 %>" name="review[rating]" value="<%= i+1 %>">
                <label for="star<%= i+1 %>" class="fas fa-star"></label>
              <% end %>
            </div>
          </div>
          <div class="form-group mt-3">
            <%= form.text_area :content, class: "form-control", placeholder: "Share your insights on the experience. Other travelers would love to hear your expertise!" %>
          </div>
          <%= form.submit 'Enviar', class: "btn btn-primary mt-2" %>
        <% end %>
      <% else %>
        <p><%= link_to 'Login', new_user_session_path %> or <%= link_to 'Sign-up', new_user_registration_path %> to leave a review and rating.</p>
      <% end %>
    </div>
  </section>
</main>


<style>
  .star-rating {
    display: flex;
    flex-direction: row-reverse;
    justify-content: center;
  }

  .star-rating input[type="radio"] {
    display: none;
  }

  .star-rating label {
    font-size: 2rem;
    color: #ffd700;
    cursor: pointer;
    transition: color 0.2s;
  }

  .star-rating input[type="radio"]:checked ~ label {
    color: #ffca28;
  }

  .star-rating label:hover,
  .star-rating label:hover ~ label {
    color: #ffff20;
  }

  .product-image {
    border-radius: 1rem; /* Ajusta este valor según tus necesidades */
  }
</style>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>